Vagrant.configure ("2") do |config|
    config.vm.box = "bento/ubuntu-24.04"

    config.vm.define "control" do | server |
      server.vm.hostname = "control"
      server.vm.provider "parallels" do |p|
        p.name = "control"
        p.memory = 512
      end
      config.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
        s.inline = <<-SHELL
          echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
          echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
        SHELL
      end
    end

    (1..3) . each do | i |
      config.vm.define "server#{i}" do | server |
        server.vm.hostname = "server#{i}"
        server.vm.provider "parallels" do |p|
          p.name = "server#{i}"
          p.memory = 512
        end
        config.vm.provision "shell" do |s|
          ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
          s.inline = <<-SHELL
            echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
            echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
          SHELL
        end
      end
    end
  end
